### PR TITLE
Overview update

### PR DESCRIPTION
**Pull request by chris-giblin**
The objective here is to provide an overview in the README.md outlining the project's main goals. The next step will be to add a specification which captures design, architectural decisions, technical clarifications.

### CODE REVIEW

**Review by SeanRooooney — APPROVED** [review]

**Comment by ppatierno** [comment]
@chris-giblin can you split the markdown to have one sentence per line, please? It's always simpler for reviewing on GitHub in order to add a comment to a specific sentence and not a whole paragraph. Thanks!

**Comment by chris-giblin** [comment]
@ppatierno  gladly ... just a minute ...

**Comment by chris-giblin** [comment]
@ppatierno I just committed a version with one sentence per line.

**Review by scholzj — APPROVED** [review]

**Review by ppatierno — COMMENTED** [review]
Thanks @chris-giblin , lgtm!

**Review by ppatierno — APPROVED** [review]

**Pull request merged**
